# Generated by Django 4.2 on 2025-09-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='usuario_default', max_length=150, unique=True),
        ),
    ]
