# Generated by Django 4.2 on 2025-08-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RHFuncionario",
            fields=[
                (
                    "fun_chapa",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("fun_nome", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "vw_colaborador",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EntradaColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rh_func_chapa", models.CharField(max_length=20)),
                ("motivo", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=7,
                    ),
                ),
                ("horario_registrado", models.DateTimeField()),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "entrada_colaborador",
            },
        ),
        migrations.CreateModel(
            name="Finalidade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("cpf", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Portaria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("placa", models.CharField(max_length=255)),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                ("data_saida", models.DateTimeField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portaria.empresa",
                    ),
                ),
                (
                    "finalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portaria.finalidade",
                    ),
                ),
                (
                    "nota_entrada",
                    models.ManyToManyField(
                        blank=True,
                        related_name="portarias_de_entrada",
                        to="Portaria.notafiscal",
                    ),
                ),
                (
                    "nota_saida",
                    models.ManyToManyField(
                        blank=True,
                        related_name="portarias_de_saida",
                        to="Portaria.notafiscal",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Portaria.visitante",
                    ),
                ),
            ],
        ),
    ]
